---
name: "ci"

on:
    pull_request: {}
    push:
        branches:
            - "main"

env:
    CI: true

jobs:
    run:
        runs-on: "ubuntu-20.04"

        steps:
            - uses: "actions/checkout@v2"
            - uses: "pnpm/action-setup@v2.0.1"
              with:
                  version: "latest"
            - uses: "actions/setup-node@v2"
              with:
                  node-version-file: ".nvmrc"
                  cache: "pnpm"
            - uses: "denoland/setup-deno@v1"
              with:
                  deno-version: "1.19.3"
            - run: "make install"
            - run: "make lint"
